### ISSUE TITLE
Wrong sign when reading signal from Dymola result file

### ISSUE THREAD

**Issue by ghost** [ScientificDataFormat/SDF-Python#1]
Hi!

I created an example model in Dymola for simulating a battery cell using the DS Battery Library 2.0.
When I read the data from the simulation result file in Python using the SDF module, the values of the cell voltage are negative. In Dymola the cell voltage only has positve values, as expected. I also checked the result file in the SDF Editor and there the voltage is positive as well. I think the sign changes when reading the data from the .mat-File via SDF-Python. I checked different signals, but all had the right sign.

Thank you for your help!

[SimResultFileAndPythonScript.zip](https://github.com/ScientificDataFormat/SDF-Python/files/2468572/SimResultFileAndPythonScript.zip)

**Comment by t-sommer** [comment]
This problem is resolved with 5fdb345cda5d138bc250070b2ac328f27962d2f7

Thanks for your help @c-hckl!
