### ISSUE TITLE
Scale assignment fails using sdf.save() - AttributeError

### ISSUE THREAD

**Issue by nilsmodrow** [ScientificDataFormat/SDF-Python#4]
The example code below raises the error:
AttributeError: 'Dataset' object has no attribute 'make_scale'

The installed package versions are:
h5py                      2.9.0
hdf5                      1.10.4
sdf                         0.3.5

Example code:

```python
import sdf
import numpy as np

g = sdf.Group(name='/')

scale = sdf.Dataset(name='scale',
                    data=np.array([4, 5, 6]),
                    is_scale=True)
array = sdf.Dataset(name='array',
                    data=np.array([1, 2, 3]),
                    scales=[scale])

g.datasets.append(scale)
g.datasets.append(array)

sdf.save('test.sdf', g)
```

**Comment by t-sommer** [comment]
Fixed with 172c7aaf86cece7272e6ca795e4b5bfa4daae336.
